### ISSUE TITLE
Trouble getting results from point query tool

### ISSUE THREAD

**Issue by kristinschrader** [glos/myglos#242]
Got a call from Stefan in Racine who can't get data from the point query tool. I tried to replicate his query and neither could I. Anyone?

**Comment by kkoch** [comment]
Ditto - I'm not getting any responses (not sure the exact steps the user was attempting but I tried selecting a point from the map and it didn't do anything).  @tslawecki or @gcutrell is this a server needs to be kicked issue?

@kristinschrader perhaps you also could list here what the user tried so we can replicate exactly?

**Comment by kristinschrader** [comment]
I tried to replicate his query on my machine in case it was a browser issue.

I opened the tool, added the lat long, picked his parameters and tried to
get data. It opened another window, but nothing ever came of it.

Kristin Schrader
Great Lakes Observing System
NOAA Great Lakes Environmental Research Lab
734-741-2294
glos.us <http://www.glos.us>




Like our Facebook page
<https://www.facebook.com/GreatLakesObservingSystem/?ref=aymt_homepage_panel>
Follow our Twitter feed <https://twitter.com/GLOSystem>

**Comment by cheryldmorse** [comment]
This should be fixed now. The TDS PQT cache was corrupt - probably occurred when the 6 hr files were replaced with the 50 day files. I stopped TDS, deleted the PQT cache and restarted TDS. I'm now getting results returned

**Comment by kkoch** [comment]
@cheryldmorse I still don't get results when I click on the map (select point) - although the fill in the value part seems to be working. Thoughts?

**Comment by kkoch** [comment]
Looks like we are still having significant issues @tslawecki @cheryldmorse 

From User > "I'm trying to download a rather substantial amount of data using the point query tool, but I'm having problems getting anything to work. I'm only trying to get 1 year of data per request, which I haven't had issues with in the past. Do you have any recommendations? Is the traffic just unusually high right now?"

**Comment by tslawecki** [comment]
Please get a little more detail on the query ... which lake and wichi model?



________________________________

**Comment by kkoch** [comment]
Message sent to user.

**Comment by kkoch** [comment]
User response:

_"I can only get the data portal to work about 1 in 5 tries. I've tried several different points and various start and end dates with no luck. I always get this error_: 
![image](https://user-images.githubusercontent.com/6392982/44344427-b24be700-a45e-11e8-9763-c445bf01d2d1.png)

Here is an example of a query that only worked sporadically this morning. By that, I mean that I can submit the same query over and over with varying levels of success:
![image](https://user-images.githubusercontent.com/6392982/44344445-b8da5e80-a45e-11e8-964c-8676d4629705.png)

_"If I only wanted one point, this wouldn't really be an issue. I'm hoping that I can pull a rather substantial amount of data from the server using a matlab script, so the lack of consistency is just making things difficult. 
Anyway, I get that this is a pretty atypical use, so it might not rank as a priority. I appreciate you looking at this for me. 
-David"_

**Comment by kkoch** [comment]
@tslawecki (see above) and then my non-related issue in troubleshooting using the map to 'select a point' not working... I tested in FF, Chrome, IE.  FF/Chrome just doesn't work (no error); IE gives me a pink box with 'x's for the map image.

![image](https://user-images.githubusercontent.com/6392982/44344780-8715c780-a45f-11e8-9756-039ecda90798.png)

**Comment by gcutrell** [comment]
@kkoch I'm not seeing the pink screen for the map. @tslawecki The GLCFS issue seems to be related to how much much data is in the query. If you take Kathy's query and just select wave height it takes a while like normal but it works consistently. Hard to tell how long this has been going on. I doubt there are many users trying to get large chunks of data from the PQT.

**Comment by kkoch** [comment]
I wasn't even trying to select data.  Just clicking on the 'pick a point' option from the map. And yes it is still pink for me today.  

![image](https://user-images.githubusercontent.com/6392982/44404413-ce19c080-a524-11e8-923a-932e077b7c3d.png)

**Comment by kkoch** [comment]
@gcutrell @tslawecki @kknee Stephen (user at top of this thread) who reported the initial problems) sent a screenshot from Friday that he is still having issues connecting.  I've checked via all three browsers today and didn't have any issues downloading data with a specific query.  I've responded back to user asking him to let me know if he's still seeing the issue today. 

![image](https://user-images.githubusercontent.com/6392982/44662510-f5b4d100-a9db-11e8-882e-012dd7e3d408.png)

My main thought on this is that we obviously have people using the product so need to check regarding robustness (as well as the additional problems above with large amounts of data and the map not working - which makes me think maybe we need to remove that option?)
